services:
  app:
    build: .
    environment:
      - TZ=Asia/Tehran
      - BOT_TOKEN
      - CHAT_ID
      - PRIVATE_CHAT_ID
      - PYTHONUNBUFFERED=1
      - GHEYMAT_CHAND_PROFILE=production
    env_file:
      - .env
    restart:
      always
    networks:
      - firefly_firefly_network
  api:
    build:
      context: .
      dockerfile: apiDockerfile
    restart:
      always
    networks:
      - firefly_firefly_network
    ports:
      - 8000:5000
networks:
  firefly_firefly_network:
    external: true
