services:
  app:
    build: .
    environment:
      - TZ=Asia/Tehran
      - BOT_TOKEN
      - CHAT_ID
      - PRIVATE_CHAT_ID
      - PYTHONUNBUFFERED=1
      - GHEYMAT_CHAND_PROFILE=production
    env_file:
      - .env
    restart:
      always
    